/*!
    *
    * Wijmo Library 5.20192.631
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

var __extends=this&&this.__extends||function(){var e=function(t,r){return(e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(t,r)};return function(t,r){function o(){this.constructor=t}e(t,r),t.prototype=null===r?Object.create(r):(o.prototype=r.prototype,new o)}}();import{WjComponentBehavior}from"wijmo/wijmo.vue2.base";import*as VueModule from"vue";import*as wjcChartRadar from"wijmo/wijmo.chart.radar";import VueModuleDefault from"vue";export var Vue=VueModuleDefault||VueModule;var WjFlexRadarBehavior=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return __extends(t,e),t.prototype._updateControl=function(t,r){switch(t){case"tooltipContent":this.control.tooltip.content=r;break;case"labelContent":this.control.dataLabel.content=r;break;default:e.prototype._updateControl.call(this,t,r)}},t.tag="wj-flex-radar",t.props=["control","isDisabled","binding","footer","header","selectionMode","palette","plotMargin","footerStyle","headerStyle","tooltipContent","itemsSource","bindingX","interpolateNulls","legendToggle","symbolSize","options","selection","itemFormatter","labelContent","chartType","startAngle","totalAngle","reversed","stacking"],t.events=["initialized","gotFocus","lostFocus","refreshing","refreshed","rendering","rendered","itemsSourceChanging","itemsSourceChanged","seriesVisibilityChanged"],t.changeEvents={selectionChanged:["selection"]},t.classCtor=function(){return wjcChartRadar.FlexRadar},t}(WjComponentBehavior);export var WjFlexRadar=WjFlexRadarBehavior.register();var WjFlexRadarAxisBehavior=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return __extends(t,e),t.tag="wj-flex-radar-axis",t.parentProp="axes",t.props=["wjProperty","control","axisLine","format","labels","majorGrid","majorTickMarks","majorUnit","max","min","position","reversed","title","labelAngle","minorGrid","minorTickMarks","minorUnit","origin","logBase","plotArea","labelAlign","name","overlappingLabels","labelPadding","itemFormatter","itemsSource","binding"],t.events=["initialized","rangeChanged"],t.classCtor=function(){return wjcChartRadar.FlexRadarAxis},t}(WjComponentBehavior);export var WjFlexRadarAxis=WjFlexRadarAxisBehavior.register();var WjFlexRadarSeriesBehavior=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return __extends(t,e),t.tag="wj-flex-radar-series",t.parentProp="series",t.siblingId="series",t.props=["wjProperty","control","axisX","axisY","binding","bindingX","cssClass","name","altStyle","symbolMarker","symbolSize","symbolStyle","visibility","itemsSource","interpolateNulls","tooltipContent","itemFormatter","chartType"],t.events=["initialized","rendering","rendered"],t.changeEvents={"chart.seriesVisibilityChanged":["visibility"]},t.classCtor=function(){return wjcChartRadar.FlexRadarSeries},t}(WjComponentBehavior);export var WjFlexRadarSeries=WjFlexRadarSeriesBehavior.register();