export class MstCustomer {
	id: number;
	customerCode: string;
	lastName: string;
	firstName: string;
	middleName: string;
	fullName: string;
	civilStatus: string;
	gender: string;
	birthDate: string;
	citizen: string;
	tin: string;
	idType: string;
	idNumber: string;
	address: string;
	city: string;
	province: string;
	country: string;
	zipCode: string;
	emailAddress: string;
	telephoneNumber: string;
	mobileNumber: string;
	employer: string;
	employerIndustry: string;
	noOfYearsEmployed: number;
	position: string;
	employmentStatus: string;
	employerAddress: string;
	employerCity: string;
	employerProvince: string;
	employerCountry: string;
	employerZipCode: string;
	employerTelephoneNumber: string;
	employerMobileNumber: string;
	spouseLastName: string;
	spouseFirstName: string;
	spouseMiddleName: string;
	spouseBirthDate: string;
	spouseCitizen : string;
	spouseEmployer : string;
	spouseTIN : string;
	remarks: string;
	status: string;
	picture: string;
	isLocked: boolean;
	createdBy: number;
	createdDateTime: string;
	updatedBy: number;
	updatedDateTime: string;
}