/*
    *
    * Wijmo Library 5.20173.380
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
define(["require","exports","wijmo/wijmo.vue2.base","wijmo/wijmo.input","wijmo/wijmo.vue2.input","vue","vue"],function(t,e,i,o,n,p,u){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),window.wijmo=window.wijmo||{},window.wijmo.vue2=window.wijmo.vue2||{},window.wijmo.vue2.input=n,e.Vue=p.default||u,e.WjComboBox=e.Vue.component("wj-combo-box",{template:"<div/>",props:i._getProps("wijmo.input.ComboBox"),mounted:function(){i._initialize(this,new o.ComboBox(this.$el))}}),e.WjAutoComplete=e.Vue.component("wj-auto-complete",{template:"<div/>",props:i._getProps("wijmo.input.AutoComplete"),mounted:function(){i._initialize(this,new o.AutoComplete(this.$el))}}),e.WjCalendar=e.Vue.component("wj-calendar",{template:"<div/>",props:i._getProps("wijmo.input.Calendar"),mounted:function(){i._initialize(this,new o.Calendar(this.$el))}}),e.WjColorPicker=e.Vue.component("wj-color-picker",{template:"<div/>",props:i._getProps("wijmo.input.ColorPicker"),mounted:function(){i._initialize(this,new o.ColorPicker(this.$el))}}),e.WjInputMask=e.Vue.component("wj-input-mask",{template:"<div/>",props:i._getProps("wijmo.input.InputMask"),mounted:function(){i._initialize(this,new o.InputMask(this.$el))}}),e.WjInputColor=e.Vue.component("wj-input-color",{template:"<div/>",props:i._getProps("wijmo.input.InputColor"),mounted:function(){i._initialize(this,new o.InputColor(this.$el))}}),e.WjMultiSelect=e.Vue.component("wj-multi-select",{template:"<div/>",props:i._getProps("wijmo.input.MultiSelect"),mounted:function(){i._initialize(this,new o.MultiSelect(this.$el))}}),e.WjMultiAutoComplete=e.Vue.component("wj-multi-auto-complete",{template:"<div/>",props:i._getProps("wijmo.input.MultiAutoComplete"),mounted:function(){i._initialize(this,new o.MultiAutoComplete(this.$el))}}),e.WjInputNumber=e.Vue.component("wj-input-number",{template:"<div/>",props:i._getProps("wijmo.input.InputNumber"),mounted:function(){i._initialize(this,new o.InputNumber(this.$el))}}),e.WjInputDate=e.Vue.component("wj-input-date",{template:"<div/>",props:i._getProps("wijmo.input.InputDate"),mounted:function(){i._initialize(this,new o.InputDate(this.$el))}}),e.WjInputTime=e.Vue.component("wj-input-time",{template:"<div/>",props:i._getProps("wijmo.input.InputTime"),mounted:function(){i._initialize(this,new o.InputTime(this.$el))}}),e.WjInputDateTime=e.Vue.component("wj-input-date-time",{template:"<div/>",props:i._getProps("wijmo.input.InputDateTime"),mounted:function(){i._initialize(this,new o.InputDateTime(this.$el))}}),e.WjListBox=e.Vue.component("wj-list-box",{template:"<div/>",props:i._getProps("wijmo.input.ListBox"),mounted:function(){i._initialize(this,new o.ListBox(this.$el))}}),e.WjMenu=e.Vue.component("wj-menu",{template:"<div/>",props:i._getProps("wijmo.input.Menu"),mounted:function(){i._initialize(this,new o.Menu(this.$el))}}),e.WjPopup=e.Vue.component("wj-popup",{template:"<div><slot/></div>",props:i._getProps("wijmo.input.Popup"),mounted:function(){i._initialize(this,new o.Popup(this.$el))}})});