/*
    *
    * Wijmo Library 5.20173.380
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
var __extends=this&&this.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])};return function(t,r){function i(){this.constructor=t}e(t,r),t.prototype=null===r?Object.create(r):(i.prototype=r.prototype,new i)}}();define(["require","exports","wijmo/wijmo.grid.detail","@angular/core","@angular/core","@angular/core","@angular/common","wijmo/wijmo.angular2.directiveBase"],function(e,t,r,i,o,n,a,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.wjFlexGridDetailMeta={selector:"[wjFlexGridDetail]",inputs:["wjFlexGridDetail","maxHeight","detailVisibilityMode","rowHasDetail","isAnimated"],outputs:["initialized"],exportAs:"wjFlexGridDetail",providers:[]};var s=function(e){function r(t,r,i,o,n,a){var s=e.call(this,i)||this;s.isInitialized=!1;s._wjBehaviour=l.WjDirectiveBehavior.attach(s,t,r,i);return s._viewContainerRef=o,s._templateRef=n,s._domRenderer=a,s._init(),s.created(),s}return __extends(r,e),r.prototype.created=function(){},r.prototype.ngOnInit=function(){this._wjBehaviour.ngOnInit()},r.prototype.ngAfterViewInit=function(){this._wjBehaviour.ngAfterViewInit()},r.prototype.ngOnDestroy=function(){this._wjBehaviour.ngOnDestroy()},r.prototype._init=function(){var e=this;this.createDetailCell=function(t,i){var o=l.WjDirectiveBehavior.instantiateTemplate(e.grid.hostElement,e._viewContainerRef,e._templateRef,e._domRenderer),n=o.viewRef,a=o.rootElement;return n.context.row=t,n.context.col=i,n.context.item=t.dataItem,a.parentElement.removeChild(a),a[r._viewRefProp]=n,a},this.disposeDetailCell=function(t){var i;if(t.detail&&(i=t.detail[r._viewRefProp])){t.detail[r._viewRefProp]=null;var o=e._viewContainerRef.indexOf(i);o>-1&&e._viewContainerRef.remove(o)}}},r._viewRefProp="__wj_viewRef",r.meta={outputs:t.wjFlexGridDetailMeta.outputs},r.decorators=[{type:o.Directive,args:[{selector:t.wjFlexGridDetailMeta.selector,inputs:t.wjFlexGridDetailMeta.inputs,outputs:t.wjFlexGridDetailMeta.outputs,exportAs:t.wjFlexGridDetailMeta.exportAs,providers:[{provide:"WjComponent",useExisting:o.forwardRef(function(){return r})}].concat(t.wjFlexGridDetailMeta.providers)}]}],r.ctorParameters=function(){return[{type:o.ElementRef,decorators:[{type:n.Inject,args:[o.ElementRef]}]},{type:o.Injector,decorators:[{type:n.Inject,args:[o.Injector]}]},{type:void 0,decorators:[{type:n.Inject,args:["WjComponent"]},{type:n.SkipSelf},{type:o.Optional}]},{type:o.ViewContainerRef,decorators:[{type:n.Inject,args:[o.ViewContainerRef]}]},{type:o.TemplateRef,decorators:[{type:n.Inject,args:[o.TemplateRef]}]},{type:o.Renderer,decorators:[{type:n.Inject,args:[o.Renderer]}]}]},r}(r.FlexGridDetailProvider);t.WjFlexGridDetail=s;var c=[s],p=function(){function e(){}return e.decorators=[{type:i.NgModule,args:[{imports:[l.WjDirectiveBaseModule,a.CommonModule],declarations:c.slice(),exports:c.slice()}]}],e.ctorParameters=function(){return[]},e}();t.WjGridDetailModule=p});