/*
    *
    * Wijmo Library 5.20173.380
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
System.register(["wijmo/wijmo.grid.detail","@angular/core","@angular/common","wijmo/wijmo.angular2.directiveBase"],function(e,t){"use strict";var r,i,o,n,a,s,c,p,u,l,d=this&&this.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])};return function(t,r){function i(){this.constructor=t}e(t,r),t.prototype=null===r?Object.create(r):(i.prototype=r.prototype,new i)}}();t&&t.id;return{setters:[function(e){r=e},function(e){i=e,o=e,n=e},function(e){a=e},function(e){s=e}],execute:function(){e("wjFlexGridDetailMeta",c={selector:"[wjFlexGridDetail]",inputs:["wjFlexGridDetail","maxHeight","detailVisibilityMode","rowHasDetail","isAnimated"],outputs:["initialized"],exportAs:"wjFlexGridDetail",providers:[]}),p=function(e){function t(t,r,i,o,n,a){var c=e.call(this,i)||this;c.isInitialized=!1;c._wjBehaviour=s.WjDirectiveBehavior.attach(c,t,r,i);return c._viewContainerRef=o,c._templateRef=n,c._domRenderer=a,c._init(),c.created(),c}return d(t,e),t.prototype.created=function(){},t.prototype.ngOnInit=function(){this._wjBehaviour.ngOnInit()},t.prototype.ngAfterViewInit=function(){this._wjBehaviour.ngAfterViewInit()},t.prototype.ngOnDestroy=function(){this._wjBehaviour.ngOnDestroy()},t.prototype._init=function(){var e=this;this.createDetailCell=function(r,i){var o=s.WjDirectiveBehavior.instantiateTemplate(e.grid.hostElement,e._viewContainerRef,e._templateRef,e._domRenderer),n=o.viewRef,a=o.rootElement;return n.context.row=r,n.context.col=i,n.context.item=r.dataItem,a.parentElement.removeChild(a),a[t._viewRefProp]=n,a},this.disposeDetailCell=function(r){var i;if(r.detail&&(i=r.detail[t._viewRefProp])){r.detail[t._viewRefProp]=null;var o=e._viewContainerRef.indexOf(i);o>-1&&e._viewContainerRef.remove(o)}}},t._viewRefProp="__wj_viewRef",t.meta={outputs:c.outputs},t.decorators=[{type:o.Directive,args:[{selector:c.selector,inputs:c.inputs,outputs:c.outputs,exportAs:c.exportAs,providers:[{provide:"WjComponent",useExisting:o.forwardRef(function(){return t})}].concat(c.providers)}]}],t.ctorParameters=function(){return[{type:o.ElementRef,decorators:[{type:n.Inject,args:[o.ElementRef]}]},{type:o.Injector,decorators:[{type:n.Inject,args:[o.Injector]}]},{type:void 0,decorators:[{type:n.Inject,args:["WjComponent"]},{type:n.SkipSelf},{type:o.Optional}]},{type:o.ViewContainerRef,decorators:[{type:n.Inject,args:[o.ViewContainerRef]}]},{type:o.TemplateRef,decorators:[{type:n.Inject,args:[o.TemplateRef]}]},{type:o.Renderer,decorators:[{type:n.Inject,args:[o.Renderer]}]}]},t}(r.FlexGridDetailProvider),e("WjFlexGridDetail",p),u=[p],l=function(){function e(){}return e.decorators=[{type:i.NgModule,args:[{imports:[s.WjDirectiveBaseModule,a.CommonModule],declarations:u.slice(),exports:u.slice()}]}],e.ctorParameters=function(){return[]},e}(),e("WjGridDetailModule",l)}}});