/*!
    *
    * Wijmo Library 5.20192.631
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

import{WjComponentBehavior}from"wijmo/wijmo.vue2.base";import*as VueModule from"vue";import*as wjcGridSheet from"wijmo/wijmo.grid.sheet";import VueModuleDefault from"vue";export var Vue=VueModuleDefault||VueModule;class WjFlexSheetBehavior extends WjComponentBehavior{}WjFlexSheetBehavior.tag="wj-flex-sheet",WjFlexSheetBehavior.props=["control","isDisabled","newRowAtTop","allowAddNew","allowDelete","allowDragging","allowMerging","allowResizing","allowSorting","quickAutoSize","autoScroll","autoSearch","autoRowHeights","autoSizeMode","autoGenerateColumns","childItemsPath","groupHeaderFormat","headersVisibility","showSelectedHeaders","showMarquee","itemFormatter","isReadOnly","imeEnabled","mergeManager","selectionMode","showGroups","showSort","showDropDown","showAlternatingRows","showErrors","alternatingRowStep","validateEdits","treeIndent","itemsSource","autoClipboard","frozenRows","frozenColumns","cloneFrozenCells","deferResizing","sortRowIndex","editColumnIndex","stickyHeaders","preserveSelectedState","preserveOutlineState","keyActionTab","keyActionEnter","rowHeaderPath","virtualizationThreshold","anchorCursor","lazyRender","refreshOnEdit","allowAutoFill","isTabHolderVisible","showFilterIcons","enableDragDrop","enableFormulas","selectedSheetIndex"],WjFlexSheetBehavior.events=["initialized","gotFocus","lostFocus","refreshing","refreshed","beginningEdit","cellEditEnded","cellEditEnding","prepareCellForEdit","formatItem","resizingColumn","resizedColumn","autoSizingColumn","autoSizedColumn","draggingColumn","draggingColumnOver","draggedColumn","sortingColumn","sortedColumn","resizingRow","resizedRow","autoSizingRow","autoSizedRow","draggingRow","draggingRowOver","draggedRow","deletingRow","deletedRow","loadingRows","loadedRows","rowEditStarting","rowEditStarted","rowEditEnding","rowEditEnded","rowAdded","groupCollapsedChanged","groupCollapsedChanging","itemsSourceChanging","itemsSourceChanged","selectionChanging","selectionChanged","scrollPositionChanged","updatingView","updatedView","updatingLayout","updatedLayout","pasting","pasted","pastingCell","pastedCell","copying","copied","draggingRowColumn","droppingRowColumn","beginDroppingRowColumn","endDroppingRowColumn","loaded","unknownFunction","sheetCleared","prepareChangingRow","prepareChangingColumn","rowChanged","columnChanged"],WjFlexSheetBehavior.changeEvents={selectedSheetChanged:["selectedSheetIndex"]},WjFlexSheetBehavior.classCtor=function(){return wjcGridSheet.FlexSheet};export var WjFlexSheet=WjFlexSheetBehavior.register();class WjSheetBehavior extends WjComponentBehavior{}WjSheetBehavior.tag="wj-sheet",WjSheetBehavior.parentProp="sheets",WjSheetBehavior.parentInCtor=!0,WjSheetBehavior.props=["wjProperty","control","name","itemsSource","visible","rowCount","columnCount"],WjSheetBehavior.events=["initialized","nameChanged"],WjSheetBehavior.classCtor=function(){return wjcGridSheet.Sheet};export var WjSheet=WjSheetBehavior.register();